# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  name: "Default"
  # demands: 
  #   - agent.name -equals instance-20250109-223217

steps:

- task: GoTool@0
  inputs:
    version: '1.23'
  displayName: "install golang"

- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'sonarconnect'
    scannerMode: 'cli'
    configMode: 'manual'
    cliProjectKey: 'kubernetes_kubernetes_89f1cddd-f66c-48d3-a885-68cefce4a5ff'
    cliSources: '.'

- script: |
    go version
    go mod tidy
    go build ./...
  displayName: 'Go Build'

- task: SonarQubeAnalyze@7
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '300'